# Generated by Django 5.1.15 on 2026-04-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.TextField(blank=True)),
                ('total_floors', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buildings_building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Unit identifier, e.g. 'A1', 'B12', 'Shop 3'.", max_length=30)),
                ('floor', models.PositiveSmallIntegerField(default=0)),
                ('unit_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('shop', 'Shop / Commercial')], default='single', max_length=30)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in KES.', max_digits=10)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied_paid', 'Occupied — Paid'), ('occupied_partial', 'Occupied — Partial'), ('occupied_unpaid', 'Occupied — Unpaid'), ('arrears', 'Arrears')], db_index=True, default='vacant', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.building')),
            ],
            options={
                'db_table': 'buildings_unit',
                'ordering': ['building__name', 'label'],
                'constraints': [models.UniqueConstraint(fields=('building', 'label'), name='unique_unit_per_building')],
            },
        ),
    ]
