# Generated by Django 5.1.15 on 2026-05-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_unit_classification'),
        ('expenses', '0003_expense_building_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['building__name', 'floor', 'label']},
        ),
        migrations.AlterField(
            model_name='unit',
            name='classification',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('BUSINESS', 'Business / Commercial')], db_index=True, default='RESIDENTIAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied_paid', 'Occupied — Paid'), ('occupied_partial', 'Occupied — Partial'), ('occupied_unpaid', 'Occupied — Unpaid'), ('arrears', 'Arrears'), ('under_maintenance', 'Under Maintenance')], db_index=True, default='vacant', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What needs to be repaired / done.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Estimated or actual cost in KES.', max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], default='open', max_length=15)),
                ('reported_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request', to='expenses.expense')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='buildings.unit')),
            ],
            options={
                'db_table': 'buildings_maintenance',
                'ordering': ['-reported_date'],
            },
        ),
    ]
