# Generated by Django 5.1.15 on 2026-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_unit_options_alter_unit_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='building',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='building',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='building',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='building',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='building',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='building',
            name='legal_name',
            field=models.CharField(blank=True, help_text="Legal entity name shown on statements, e.g. 'Wilkem Ventures Company Ltd.'", max_length=160),
        ),
        migrations.AddField(
            model_name='building',
            name='paybill_account_format',
            field=models.CharField(blank=True, help_text="Paybill account number. Use '{unit}' as a placeholder for the unit label, e.g. '90290#{unit}' or a fixed value like '839800'.", max_length=60),
        ),
        migrations.AddField(
            model_name='building',
            name='paybill_number',
            field=models.CharField(blank=True, help_text="M-Pesa Paybill business number, e.g. '400222'.", max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='postal_address',
            field=models.CharField(blank=True, help_text="Postal address line, e.g. 'PO Box 66741 - 00800, Nairobi, Kenya'.", max_length=160),
        ),
    ]
