# Generated by Django 5.1.15 on 2026-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_bank_account_building_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='statement_descriptor',
            field=models.CharField(blank=True, help_text="Right-hand cell on the rent statement, e.g. 'Unit G05 - Hospital' or 'House 3A - Donholm Estate'. Leave blank to auto-build from the unit label and building name.", max_length=80),
        ),
    ]
