# Generated by Django 5.1.15 on 2026-06-16 07:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def _dedupe_unit_labels(apps, schema_editor):
    """Make Unit.label globally unique (case-insensitive) before the
    unique_unit_label_global constraint is created.

    Pre-existing demo/seed data can reuse a label across buildings
    (e.g. 'Unit 1'), which would make the unique index fail to build. Rename
    the later duplicates so the index can be created. These rows are expected
    to be replaced by the real rent roll (load_property_data --reset)."""
    Unit = apps.get_model('buildings', 'Unit')
    seen = set()
    for unit in Unit.objects.order_by('pk').iterator():
        label = (unit.label or '').strip()
        key = label.upper()
        if key and key not in seen:
            seen.add(key)
            if label != unit.label:
                unit.label = label
                unit.save(update_fields=['label'])
            continue
        # blank or duplicate -> make unique using the pk
        new_label = (f"{label}-{unit.pk}" if label else f"UNIT-{unit.pk}")[:30]
        while new_label.upper() in seen:
            new_label = f"{new_label[:24]}-{unit.pk}"[:30]
        unit.label = new_label
        unit.save(update_fields=['label'])
        seen.add(new_label.upper())


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_unit_statement_descriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Old unit label, e.g. 'G01'.", max_length=30)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'unit aliases',
                'db_table': 'buildings_unit_alias',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, help_text="Short property code used as the prefix for this building's unit labels, e.g. 'DON', 'RB', 'MC'. Must be unique across all properties.", max_length=10, null=True, unique=True),
        ),
        migrations.RunPython(_dedupe_unit_labels, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('label'), name='unique_unit_label_global'),
        ),
        migrations.AddField(
            model_name='unitalias',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='buildings.unit'),
        ),
        migrations.AddConstraint(
            model_name='unitalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('label'), name='unique_unit_alias_label_global'),
        ),
    ]
