# Generated by Django 5.1.15 on 2026-07-14 19:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_unitalias_building_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='water_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Tariff charged per unit of water consumed (KES). Donholm bills at 150/unit.', max_digits=8),
        ),
    ]
