# Generated by Django 5.1.15 on 2026-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_water_rate_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='property_type',
            field=models.CharField(choices=[('rental', 'Rental Property'), ('farm', 'Farm (manual income + expenses)'), ('expense_only', 'Expenses Only (no income)')], default='rental', help_text='Rental (tenant rent), Farm (manual income + expenses), or Expenses-only (e.g. Baobab Karen).', max_length=16),
        ),
    ]
