# Generated by Django 5.1.15 on 2026-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_unit_combined_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='photo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='building',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
