# Generated by Django 5.1.15 on 2026-04-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_period__9b6310_idx',
            old_name='expenses_ex_period__idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_20264a_idx',
            old_name='expenses_ex_categor_idx',
        ),
    ]
