# Generated by Django 5.1.15 on 2026-04-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('expenses', '0002_rename_expenses_ex_period__idx_expenses_ex_period__9b6310_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building this expense applies to. Leave blank for portfolio-wide costs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='buildings.building'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['building'], name='expenses_ex_buildin_d47ac9_idx'),
        ),
    ]
