# Generated by Django 5.1.15 on 2026-05-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_coa_hierarchy_wilkem_rentals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='GL code (e.g. 5200 Repairs & Maintenance).', max_length=8, unique=True),
        ),
    ]
