# Generated by Django 5.1.15 on 2026-07-15 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_building_property_type'),
        ('expenses', '0007_expense_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the income was received.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='GL income account this posts to (4xxx).', limit_choices_to={'account_type': 'income', 'is_header': False}, on_delete=django.db.models.deletion.PROTECT, related_name='manual_income', to='expenses.account')),
                ('building', models.ForeignKey(help_text='Property this income belongs to (a farm).', on_delete=django.db.models.deletion.PROTECT, related_name='manual_income', to='buildings.building')),
            ],
            options={
                'db_table': 'expenses_manual_income',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='expenses_ma_period__983903_idx'), models.Index(fields=['building'], name='expenses_ma_buildin_374429_idx')],
            },
        ),
    ]
