# Generated by Django 5.1.15 on 2026-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_unit_monthly_rent_non_negative'),
        ('expenses', '0009_farm_accounts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='expense_period_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='manualincome',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='manual_income_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='manualincome',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='manual_income_period_month_valid'),
        ),
    ]
