# Generated by Django 6.0.6 on 2026-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='ledger_jour_period__7602b2_idx',
            old_name='ledger_je_period_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='ledger_jour_buildin_b75701_idx',
            old_name='ledger_je_building_period_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='ledger_jour_source__96cd90_idx',
            old_name='ledger_je_source_idx',
        ),
    ]
