# Generated by Django 5.1.15 on 2026-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_ledger_je_period_idx_ledger_jour_period__7602b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('reversal', 'Reversal')], default='normal', max_length=10)),
                ('operation', models.CharField(choices=[('post', 'Post'), ('reverse', 'Reverse')], default='post', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ledger_posting_failure',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['resolved'], name='ledger_post_resolve_a5a8ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'kind'), name='unique_posting_failure_per_source_kind')],
            },
        ),
    ]
