# Generated by Django 5.1.15 on 2026-08-01 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresettoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Director'), ('accountant', 'Accountant'), ('caretaker', 'Caretaker'), ('viewer', 'Viewer (read-only)')], default='viewer', help_text='Least privilege by default: a new account can read but not record, waive, or void anything until it is explicitly promoted.', max_length=12),
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Dotted action name, e.g. 'payment.void', 'arrears.waive'.", max_length=40)),
                ('object_type', models.CharField(help_text="Model acted on, e.g. 'payment'.", max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(help_text='Human-readable one-line description.', max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action. Null for system/automated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_financial_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='accounts_fi_object__27b48c_idx'), models.Index(fields=['action', '-created_at'], name='accounts_fi_action_bfc4b4_idx'), models.Index(fields=['actor', '-created_at'], name='accounts_fi_actor_i_1eded2_idx')],
            },
        ),
    ]
