# Generated by Django 5.1.15 on 2026-09-28 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FINANCIAL_PREFIXES = (
    "payment.", "arrears.", "credit.", "refund.", "expense.", "manual_income.",
    "utility_charge.", "tenant.deposit", "billing.",
)


def backfill(apps, schema_editor):
    """Rows written before this migration were all money actions by named people."""
    AuditLog = apps.get_model("accounts", "AuditLog")
    for row in AuditLog.objects.select_related("actor").iterator():
        row.is_financial = row.action.startswith(FINANCIAL_PREFIXES)
        if row.actor_id:
            u = row.actor
            row.actor_label = f"{u.first_name} {u.last_name}".strip() or u.email
            row.actor_role = u.role
        # Everything before now was either a dashboard action or reconcile_donholm.
        row.source = "command" if row.action == "payment.reallocate" else "web"
        row.save(update_fields=["is_financial", "actor_label", "actor_role", "source"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_financialauditlog_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_financial',
            field=models.BooleanField(default=False, help_text='Moves or changes money, rent, deposits or charges.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='kind',
            field=models.CharField(choices=[('event', 'Action'), ('change', 'Record change'), ('auth', 'Sign-in'), ('denied', 'Refused')], db_index=True, default='event', max_length=8),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_label',
            field=models.CharField(blank=True, help_text="What the object was called at the time, e.g. 'MCF01'.", max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Rows written by the same request or command share this.', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='One per sign-in; every action taken under that sign-in shares it.', max_length=32),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source',
            field=models.CharField(db_index=True, default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_detail',
            field=models.CharField(blank=True, help_text='Command name, scheduled job, or request path.', max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text="Dotted action name, e.g. 'payment.void', 'unit.update'.", max_length=60),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Who performed the action. Null for system/automated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(help_text="Model acted on, e.g. 'payment'.", max_length=40),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
