# Generated by Django 5.1.15 on 2026-04-11 07:25

import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(help_text='National ID or passport number.', max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Agreed rent in KES. Defaults to unit rent at move-in, but can differ.', max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('moved_out', 'Moved Out'), ('archived', 'Archived')], db_index=True, default='active', max_length=15)),
                ('move_out_notes', models.TextField(blank=True, help_text='Notes recorded at move-out (condition, damages, deposit return).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='buildings.unit')),
            ],
            options={
                'db_table': 'tenants_tenant',
                'ordering': ['-move_in_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_front', 'ID Front'), ('id_back', 'ID Back'), ('passport', 'Passport'), ('lease', 'Lease Agreement'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=apps.tenants.models.tenant_document_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
