# Generated by Django 5.1.15 on 2026-05-03 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-status', '-move_in_date']},
        ),
        migrations.AddField(
            model_name='tenant',
            name='deposit_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated refund amount at move-out time.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='deposit_refund_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentage of deposit to refund on move-out (0-100).', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of the month the rent is due (1-31). Defaults to 5th.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='intended_move_out_date',
            field=models.DateField(blank=True, help_text="Tenant's stated intended move-out date.", null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notice_date',
            field=models.DateField(blank=True, help_text='Date move-out notice was given.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='move_out_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('notice_given', 'Notice Given'), ('moved_out', 'Moved Out'), ('archived', 'Archived')], db_index=True, default='active', max_length=15),
        ),
    ]
