# Generated by Django 5.1.15 on 2026-05-12 17:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options_tenant_deposit_refund_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='kra_pin',
            field=models.CharField(blank=True, help_text="KRA PIN shown on rent statements (e.g. 'A007523148T'). Optional.", max_length=20, validators=[django.core.validators.RegexValidator(message="KRA PIN must look like 'A007523148T' — a letter, 9 digits, then a letter.", regex='^[AP]\\d{9}[A-Z]$')]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_notes',
            field=models.TextField(blank=True, help_text='Reviewer notes / rejection reason.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_front', 'ID Front'), ('id_back', 'ID Back'), ('passport', 'Passport'), ('kra_pin_certificate', 'KRA PIN Certificate'), ('lease', 'Lease Agreement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
