# Generated by Django 5.1.15 on 2026-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_kra_pin_tenant_kyc_notes_tenant_kyc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='care_of',
            field=models.CharField(blank=True, help_text="'c/o' line shown on the rent statement (e.g. 'David Chibeka').", max_length=120),
        ),
    ]
