# Generated by Django 5.1.15 on 2026-09-01 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_unit_monthly_rent_non_negative'),
        ('tenants', '0005_tenant_agreed_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gte', 0)), name='tenant_monthly_rent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_paid__gte', 0)), name='tenant_deposit_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 31)), name='tenant_due_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_refund_percentage__gte', 0), ('deposit_refund_percentage__lte', 100)), name='tenant_deposit_refund_percentage_valid'),
        ),
    ]
