# Generated by Django 5.1.15 on 2026-09-24 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_water_rate_per_building'),
        ('tenants', '0007_tenant_is_billable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'notice_given'])), fields=('id_number',), name='tenant_id_number_unique_while_current'),
        ),
    ]
