# Generated by Django 5.1.15 on 2026-04-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('expected_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='expected_rent - amount_paid. Positive = owed.', max_digits=10)),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrears', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_arrears',
                'ordering': ['-period_year', '-period_month'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period_month', 'period_year'), name='unique_arrears_per_period')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('period_month', models.PositiveSmallIntegerField(help_text='Month the payment applies to (1-12).')),
                ('period_year', models.PositiveIntegerField(help_text='Year the payment applies to.')),
                ('source', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa TransID, bank ref, or receipt number.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'period_year', 'period_month'], name='payments_pa_tenant__cf9388_idx'), models.Index(fields=['reference'], name='payments_pa_referen_75358f_idx')],
            },
        ),
    ]
