# Generated by Django 5.1.15 on 2026-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_transac_e96a4f_idx',
            old_name='tx_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_tenant__34fed4_idx',
            old_name='tx_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payments_tr_unit_cl_53b116_idx',
            old_name='tx_classification_idx',
        ),
        migrations.AddField(
            model_name='arrears',
            name='waive_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrears',
            name='waived_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_code',
            field=models.CharField(blank=True, help_text='External reference stored exactly as received (M-Pesa TransID, bank ref…).', max_length=100),
        ),
    ]
