# Generated by Django 5.1.15 on 2026-05-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_payment_type'),
        ('tenants', '0004_tenant_care_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(help_text='Date this charge posts to the ledger.')),
                ('period_month', models.PositiveSmallIntegerField(help_text='Usage month (1-12).')),
                ('period_year', models.PositiveIntegerField()),
                ('label', models.CharField(default='Water Usage', help_text="Charge label, e.g. 'Water Usage', 'Electricity'.", max_length=60)),
                ('units', models.DecimalField(blank=True, decimal_places=2, help_text="Usage in units (m³, kWh, …). Optional; shown as '(7 units)' if present.", max_digits=10, null=True)),
                ('opening_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closing_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payments_utility_charge',
                'ordering': ['-posting_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'period_year', 'period_month'], name='payments_ut_tenant__51b109_idx')],
            },
        ),
    ]
