# Generated by Django 5.1.15 on 2026-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_utilitycharge'),
        ('tenants', '0004_tenant_care_of'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['period_year', 'period_month'], name='payments_pa_period__a3dc94_idx'),
        ),
    ]
