# Generated by Django 5.1.15 on 2026-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_payments_pa_period__a3dc94_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rental Income (4110/4120)'), ('late_fee', 'Late Fees (4200)'), ('deposit', 'Security Deposit (2100)'), ('other', 'Other Income')], default='rent', help_text='Used to split income into 4110/4120 (rent), 4200 (late fees), or 2100 (deposit liability).', max_length=10),
        ),
    ]
