# Generated by Django 5.1.15 on 2026-05-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopIpnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Co-op `TransactionId` — the unique reference for this event.', max_length=100, unique=True)),
                ('payment_ref', models.CharField(blank=True, help_text='Co-op `PaymentRef` — the unique reference for the payment.', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='`AcctNo` the credit landed in (the institution account).', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event_type', models.CharField(blank=True, help_text='`EventType` from the bank, e.g. CREDIT / DEBIT.', max_length=20)),
                ('channel', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], help_text='Inferred inflow channel (mpesa via Paybill, direct bank, …).', max_length=10)),
                ('narration', models.TextField(blank=True, help_text='Raw narration string the bill ref / payer details were parsed from.')),
                ('raw_payload', models.JSONField(help_text='The full IPN payload exactly as received.')),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored (non-credit)'), ('error', 'Error')], default='error', max_length=10)),
                ('detail', models.CharField(blank=True, help_text='Human-readable note on the outcome (why unmatched, error text, …).', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, help_text='The Payment created from this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_ipn_events', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_coop_ipn_event',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_co_transac_1ec357_idx'), models.Index(fields=['status', '-received_at'], name='payments_co_status_ddc1b3_idx')],
            },
        ),
    ]
