# Generated by Django 5.1.15 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_coopipnevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopipnevent',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored (non-credit)'), ('reversal_pending', 'Reversal — awaiting authorization'), ('error', 'Error')], default='error', max_length=20),
        ),
    ]
