# Generated by Django 5.1.15 on 2026-06-02 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_coopipnevent_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coopipnevent',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coopipnevent',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='Director who authorised this reversal (REVERSAL_PENDING → APPLIED).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coopipnevent',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('unmatched', 'Unmatched'), ('duplicate', 'Duplicate'), ('ignored', 'Ignored (non-credit)'), ('reversal_pending', 'Reversal — awaiting authorization'), ('reversal_applied', 'Reversal applied'), ('error', 'Error')], default='error', max_length=20),
        ),
    ]
