# Generated by Django 5.1.15 on 2026-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_coopipnevent_authorized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantnotification',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantnotification',
            name='provider_response',
            field=models.TextField(blank=True),
        ),
    ]
