# Generated by Django 5.1.15 on 2026-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_tenantnotification_dedupe_key_and_more'),
        ('tenants', '0004_tenant_care_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', help_text='Natural-key guard against double-booking a single payment. Set only by single-payment ingestion (the manual create/mock paths); left blank by FIFO allocation, which deliberately splits one credit into several Payment rows that share a reference. Unique when non-blank.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_payment_idempotency_key'),
        ),
    ]
