# Generated by Django 5.1.15 on 2026-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', help_text="Natural-key guard against double-booking a single payment. Single-payment ingestion (the manual create/mock paths) sets the bare reference; FIFO allocation splits one credit into several Payment rows and sets '<transaction id>#<chunk>' on each. Unique when non-blank.", max_length=100),
        ),
    ]
