# Generated by Django 5.1.15 on 2026-08-01 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_idempotency_key'),
        ('tenants', '0004_tenant_care_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_idempotency_key',
        ),
        migrations.AddField(
            model_name='arrears',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overpayment carried forward from an earlier period and applied to this one. Without it a tenant who prepaid had the excess floored to zero and was billed — and dunned — in full the following month.', max_digits=10),
        ),
        migrations.AddField(
            model_name='arrears',
            name='expected_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='16% VAT owed on top of expected_rent for BUSINESS units; 0 for residential. Commercial tenants pay rent+VAT as one figure, so the obligation a payment is measured against is expected_rent + expected_vat — comparing gross cash to base rent cleared commercial arrears 16% early and spilled the VAT into the next period as rent.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who recorded this payment. Null for automated (bank IPN) ingestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arrears',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='expected_total - (amount_paid + waived_amount + credit_applied). Positive = owed.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='arrears',
            name='expected_rent',
            field=models.DecimalField(decimal_places=2, help_text='Rent billed for the period, VAT-EXCLUSIVE (the base rent).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', help_text="Natural-key guard against double-booking a single payment. Single-payment ingestion (the manual create/mock paths) sets the bare reference; FIFO allocation splits one credit into several Payment rows and sets '<transaction id>#<chunk>' on each. Unique PER TENANT when non-blank — see the constraint note below.", max_length=100),
        ),
        migrations.AddIndex(
            model_name='arrears',
            index=models.Index(fields=['tenant', 'is_cleared'], name='payments_ar_tenant__ce0bae_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['voided_at'], name='payments_pa_voided__f97ad4_idx'),
        ),
        # The two Arrears CheckConstraints belonging to this model change are
        # added in 0018 instead, AFTER the 0016 recompute has healed the data
        # they assert. Adding them here failed the production deploy: a legacy
        # row carried balance = -1000.00, so the whole migration rolled back.
        # A constraint cannot be introduced before the migration that
        # establishes the invariant it checks. Do not move them back here.
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='unique_payment_idempotency_key_per_tenant'),
        ),
    ]
