# Generated by Django 5.1.15 on 2026-09-01 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_arrears_check_constraints'),
        ('tenants', '0006_tenant_tenant_monthly_rent_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='payment_period_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='utilitycharge',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_year', 'period_month', 'label'), name='unique_utility_charge_per_period'),
        ),
        migrations.AddConstraint(
            model_name='utilitycharge',
            constraint=models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='utility_charge_period_month_valid'),
        ),
    ]
